\c monster_dev

CREATE TABLE IF NOT EXISTS artists (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(1024),
  picture VARCHAR(1024),
);

CREATE TABLE IF NOT EXISTS tracks (
  id BIGSERIAL PRIMARY KEY,
  artist_id VARCHAR(1024),
  name VARCHAR(1024),
  url VARCHAR(1024),
);